name: JMeter DSL + JMX CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      # Run JMeter DSL tests via Maven
      - name: Run JMeter DSL Tests
        run: mvn -B test

      # Upload Maven test results
      - name: Upload DSL Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-dsl-reports
          path: target/

      # Install JMeter for .jmx test plans
      - name: Download and install JMeter
        run: |
          curl -L https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.zip -o jmeter.zip
          unzip jmeter.zip
          mv apache-jmeter-5.6.3 jmeter

      # Debug to confirm JMX file exists
      - name: Verify JMX files
        run: ls -R jmx || echo "No jmx directory found"

      # Run JMX test plan
      - name: Run JMX Test Plan
        run: |
          ./jmeter/bin/jmeter -n -t ./jmx/herokuApp.jmx -l results.jtl -e -o report_output

      # Upload JMX test results
      - name: Upload JMX Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-jmx-reports
          path: |
            results.jtl
            report_output/
